shell379: main.c init_shell.c init_table.c read_command.c parsing.c jobs.c single_command.c handle_origin.c with_para.c append_table.c create_process.c delete_process.c printPT.c search_process.c
	gcc -o shell379 main.c init_shell.c init_table.c read_command.c parsing.c jobs.c single_command.c handle_origin.c with_para.c append_table.c create_process.c delete_process.c printPT.c search_process.c
